[build]
  publish = "pages"
  command = ""

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/theme.js"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
